import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={apiKey:'AIzaSyCR6nPQIG9GLgbiLCVCZOc785j8BMicwQA',authDomain:'island-journey-rgb.firebaseapp.com',projectId:'island-journey-rgb',messagingSenderId:'840035091382',storageBucket:'island-journey-rgb.firebasestorage.app'},ADMIN_EMAIL='info@rgb-workshop.com',ENDPOINT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/peaceBunWhack';
const auth=getAuth(initializeApp(FIREBASE_CONFIG)),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);let config;
const textLabels={pageTitle:'瀏覽器標題',brandLine:'標題上方英文',brandMain:'主標題',brandSub:'副標題',timeLabel:'時間標籤',scoreLabel:'得分標籤',scoreUnit:'分數單位',targetLabel:'目標分數標籤',pauseButtonLabel:'暫停按鈕輔助文字',helpTitle:'玩法說明標題',helpText:'玩法說明內容',bunLegend:'平安包名稱',tartLegend:'蛋撻名稱',startEyebrow:'開始畫面英文',startTitle:'開始畫面標題',startText:'開始畫面說明',startButton:'開始按鈕',pauseEyebrow:'暫停畫面英文',pauseTitle:'暫停標題',resumeButton:'繼續按鈕',completeEyebrow:'成功畫面英文',successTitle:'成功標題',timeUpEyebrow:'時間到英文',timeUpTitle:'時間到標題',successText:'成功說明',timeUpText:'未達標說明（可用 {score}）',retryButton:'再玩一次按鈕',returnButton:'回到故事按鈕',returningButton:'返回中文字'};
const settingLabels={difficulty:'難度',duration:'遊戲時間（秒）',targetScore:'目標分數',bunPoints:'平安包加分',tartPenalty:'蛋撻扣分',tartChance:'蛋撻出現率（%）'};
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}async function loadPublished(){const r=await fetch(ENDPOINT,{cache:'no-store'});if(r.status===404)return fallback();if(!r.ok)throw new Error(`讀取失敗 (${r.status})`);const d=await r.json(),payload=d.fields?.payload?.stringValue;return payload?JSON.parse(payload):fallback()}
function msg(target,text,error=false){target.textContent=text;target.classList.toggle('error',error)}
function render(){const textBox=$('#textFields'),settingBox=$('#settingFields');textBox.innerHTML='';settingBox.innerHTML='';Object.entries(textLabels).forEach(([key,label])=>{const field=document.createElement('label');field.textContent=label;const input=document.createElement(key.endsWith('Text')?'textarea':'input');input.dataset.textKey=key;input.value=config.texts[key]||'';field.appendChild(input);textBox.appendChild(field)});Object.entries(settingLabels).forEach(([key,label])=>{const field=document.createElement('label');field.textContent=label;let input;if(key==='difficulty'){input=document.createElement('select');input.innerHTML='<option value="easy">容易</option><option value="normal">中等</option><option value="hard">困難</option>'}else{input=document.createElement('input');input.type='number';input.min='0';input.step=key==='tartChance'?'1':'1'}input.dataset.settingKey=key;input.value=config.settings[key];field.appendChild(input);settingBox.appendChild(field)})}
function readForm(){document.querySelectorAll('[data-text-key]').forEach(x=>config.texts[x.dataset.textKey]=x.value.trim());document.querySelectorAll('[data-setting-key]').forEach(x=>config.settings[x.dataset.settingKey]=x.tagName==='SELECT'?x.value:Number(x.value))}
async function reload(){msg($('#saveMessage'),'正在載入…');try{config=await loadPublished();render();msg($('#saveMessage'),'已載入目前公開設定。')}catch(e){msg($('#saveMessage'),e.message,true)}}
async function publish(e){e.preventDefault();readForm();config.settings.tartChance=Math.max(0,Math.min(100,config.settings.tartChance));msg($('#saveMessage'),'正在發佈…');try{const token=await auth.currentUser.getIdToken(true),r=await fetch(ENDPOINT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!r.ok)throw new Error(`發佈失敗 (${r.status}) ${await r.text()}`);msg($('#saveMessage'),'發佈成功！前台重新開啟後會使用新設定。')}catch(e){msg($('#saveMessage'),e.message,true)}}
$('#loginButton').onclick=async()=>{msg($('#loginMessage'),'正在開啟 Google 登入…');try{await signInWithPopup(auth,provider)}catch(e){msg($('#loginMessage'),`登入失敗：${e.message}`,true)}};$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;onAuthStateChanged(auth,async user=>{const ok=user?.email?.toLowerCase()===ADMIN_EMAIL&&user.emailVerified;if(user&&!ok){await signOut(auth);msg($('#loginMessage'),`此帳戶沒有管理權限：${user.email}`,true);return}$('#login').hidden=!!ok;$('#editor').hidden=!ok;$('#logout').hidden=!ok;if(ok){$('#userEmail').textContent=user.email;await reload()}});
