import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={apiKey:'AIzaSyCR6nPQIG9GLgbiLCVCZOc785j8BMicwQA',authDomain:'island-journey-rgb.firebaseapp.com',projectId:'island-journey-rgb',messagingSenderId:'840035091382',storageBucket:'island-journey-rgb.firebasestorage.app'},ADMIN_EMAIL='info@rgb-workshop.com',ENDPOINT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/peaceBunWhack',auth=getAuth(initializeApp(FIREBASE_CONFIG)),provider=new GoogleAuthProvider(),$=s=>document.querySelector(s);let config;
const textLabels={pageTitle:'瀏覽器標題',brandLine:'標題上方英文',brandMain:'主標題',brandSub:'副標題',levelLabel:'關卡標籤',timeLabel:'時間標籤',scoreLabel:'得分標籤',accuracyLabel:'命中率標籤',scoreUnit:'分數單位',minuteUnit:'分鐘單位',pauseButtonLabel:'暫停按鈕輔助文字',helpTitle:'玩法說明標題',helpText:'玩法說明內容',bunLegend:'平安包計數名稱',tartLegend:'蛋撻名稱',loadingTitle:'預載畫面文字',startEyebrow:'開始畫面英文',startTitle:'開始畫面標題',startText:'開始畫面說明',startButton:'開始按鈕',levelName:'關卡名稱（可用 {level}）',pauseEyebrow:'暫停畫面英文',pauseTitle:'暫停標題',resumeButton:'繼續按鈕',levelCompleteEyebrow:'過關英文',levelFailedEyebrow:'未過關英文',levelSuccessTitle:'過關標題（可用 {level}）',levelFailedTitle:'未過關標題（可用 {level}）',accuracyResult:'命中結果（可用 {hits} {total} {accuracy} {target}）',levelRewardText:'過關獎勵文字（可用 {reward} {score}）',levelRetryText:'重玩提示（可用 {target}）',retryLevelButton:'重玩本關按鈕',nextLevelButton:'下一關按鈕',viewResultButton:'查看總成績按鈕',completeEyebrow:'完成三關英文',successTitle:'完成三關標題',successText:'完成說明（可用 {score}）',retryButton:'重新挑戰按鈕',returnButton:'回到故事按鈕',returningButton:'返回中文字'};
const settingLabels={tartPenalty:'打中蛋撻扣分',tartChance:'蛋撻出現率（%）'},levelDefs=[['duration','限時（秒）','每關 120 秒即兩分鐘'],['requiredAccuracy','過關命中率（%）','70 代表要打中 70% 平安包'],['reward','過關獎勵分數','成功過關後一次加入'],['spawnEveryMs','每次出現間隔（毫秒）','越小越快；例如 760 比 430 慢'],['visibleForMs','平安包停留時間（毫秒）','越小越快縮回洞內'],['doubleChance','同時出現兩個機率','0.20 代表 20%']];
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}async function loadPublished(){const base=await fallback(),r=await fetch(ENDPOINT,{cache:'no-store'});if(!r.ok)return base;const d=await r.json(),p=d.fields?.payload?.stringValue,remote=p?JSON.parse(p):null;return remote?.version>=3?remote:base}function msg(target,text,error=false){target.textContent=text;target.classList.toggle('error',error)}
function field(label,value,type='text',help=''){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement(type==='textarea'?'textarea':'input');if(type==='number')input.type='number';input.value=value??'';wrap.append(input);if(help){const small=document.createElement('small');small.textContent=help;wrap.append(small)}return{wrap,input}}
function render(){const textBox=$('#textFields'),settingBox=$('#settingFields'),levelBox=$('#levelFields');textBox.innerHTML='';settingBox.innerHTML='';levelBox.innerHTML='';Object.entries(textLabels).forEach(([key,label])=>{const x=field(label,config.texts[key]||'',key.endsWith('Text')?'textarea':'text');x.input.dataset.textKey=key;textBox.append(x.wrap)});Object.entries(settingLabels).forEach(([key,label])=>{const x=field(label,config.settings[key],'number',key==='tartChance'?'0 至 100':'只扣分，不影響平安包命中率');x.input.dataset.settingKey=key;settingBox.append(x.wrap)});config.levels.forEach((level,i)=>{const card=document.createElement('article');card.className='level-card';const h=document.createElement('h3');h.textContent=`第 ${i+1} 關`;card.append(h);const grid=document.createElement('div');grid.className='setting-grid';levelDefs.forEach(([key,label,help])=>{const x=field(label,level[key],'number',help);x.input.dataset.level=i;x.input.dataset.levelKey=key;x.input.step=key==='doubleChance'?'0.01':'1';grid.append(x.wrap)});card.append(grid);levelBox.append(card)})}
function readForm(){document.querySelectorAll('[data-text-key]').forEach(x=>config.texts[x.dataset.textKey]=x.value.trim());document.querySelectorAll('[data-setting-key]').forEach(x=>config.settings[x.dataset.settingKey]=Number(x.value));document.querySelectorAll('[data-level-key]').forEach(x=>config.levels[+x.dataset.level][x.dataset.levelKey]=Number(x.value))}
async function reload(){msg($('#saveMessage'),'正在載入…');try{config=await loadPublished();render();msg($('#saveMessage'),'已載入目前公開設定。')}catch(e){msg($('#saveMessage'),e.message,true)}}
async function publish(e){e.preventDefault();readForm();config.version=3;config.settings.tartChance=Math.max(0,Math.min(100,config.settings.tartChance));config.levels.forEach(l=>{l.requiredAccuracy=Math.max(0,Math.min(100,l.requiredAccuracy));l.doubleChance=Math.max(0,Math.min(1,l.doubleChance))});msg($('#saveMessage'),'正在發佈…');try{const token=await auth.currentUser.getIdToken(true),r=await fetch(ENDPOINT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)},updatedAt:{timestampValue:new Date().toISOString()}}})});if(!r.ok)throw new Error(`發佈失敗 (${r.status}) ${await r.text()}`);msg($('#saveMessage'),'發佈成功！前台重新開啟後會使用新設定。')}catch(e){msg($('#saveMessage'),e.message,true)}}
$('#loginButton').onclick=async()=>{msg($('#loginMessage'),'正在開啟 Google 登入…');try{await signInWithPopup(auth,provider)}catch(e){msg($('#loginMessage'),`登入失敗：${e.message}`,true)}};$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;onAuthStateChanged(auth,async user=>{const ok=user?.email?.toLowerCase()===ADMIN_EMAIL&&user.emailVerified;if(user&&!ok){await signOut(auth);msg($('#loginMessage'),`此帳戶沒有管理權限：${user.email}`,true);return}$('#login').hidden=!!ok;$('#editor').hidden=!ok;$('#logout').hidden=!ok;if(ok){$('#userEmail').textContent=user.email;await reload()}});
