const $=s=>document.querySelector(s),holes=$('#holes');let cfg,state='idle',score=0,timeLeft=30,timer,spawner,active=new Map(),audio;
for(let i=0;i<15;i++){const hole=document.createElement('button');hole.type='button';hole.className='hole';hole.setAttribute('aria-label',`洞口 ${i+1}`);hole.innerHTML='<span class="object"><img alt=""></span>';hole.onclick=e=>whack(i,e);holes.appendChild(hole)}
const holeEls=[...document.querySelectorAll('.hole')];
async function load(){try{cfg=await(await fetch('config.json',{cache:'no-store'})).json()}catch{cfg={duration:30,targetScore:500,bunPoints:40,tartPenalty:20,tartChance:.18,spawnEveryMs:520,visibleForMs:920}}timeLeft=cfg.duration;$('#time').textContent=timeLeft;$('#target').textContent=cfg.targetScore}
function tone(freq,duration=.08){try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration)}catch{}}
function spawn(){if(state!=='running')return;const free=holeEls.map((_,i)=>i).filter(i=>!active.has(i));if(!free.length)return;const count=Math.random()<.28?2:1,tartChance=Number.isFinite(+cfg.tartChance)?+cfg.tartChance:.18;for(let n=0;n<count&&free.length;n++){const pick=Math.floor(Math.random()*free.length),index=free.splice(pick,1)[0],isTart=Math.random()<tartChance,life=cfg.visibleForMs*(isTart?.9:1),img=holeEls[index].querySelector('img');img.src=isTart?'':'assets/peace-bun.png';img.alt=isTart?'':'平安包';active.set(index,{isTart,hit:false});holeEls[index].className='hole up'+(isTart?' tart':'');const timeout=setTimeout(()=>hide(index),life);active.get(index).timeout=timeout}}
function hide(index){const item=active.get(index);if(!item)return;clearTimeout(item.timeout);holeEls[index].className='hole';holeEls[index].querySelector('.feedback')?.remove();active.delete(index)}
function whack(index,event){if(state!=='running')return;const item=active.get(index);showMallet(event);if(!item||item.hit){tone(120);return}item.hit=true;clearTimeout(item.timeout);holeEls[index].classList.add('hit');const points=item.isTart?-(Number(cfg.tartPenalty)||20):(Number(cfg.bunPoints)||40);score+=points;$('#score').textContent=score;showFeedback(index,points);tone(item.isTart?150:580,.13);setTimeout(()=>hide(index),360)}
function showFeedback(index,points){const badge=document.createElement('span');badge.className='feedback'+(points<0?' penalty':'');badge.textContent=(points>0?'+':'')+points;holeEls[index].appendChild(badge)}
function showMallet(event){const box=$('#game').getBoundingClientRect(),mallet=$('#mallet');mallet.style.left=((event.clientX-box.left)/box.width*100)+'%';mallet.style.top=((event.clientY-box.top)/box.height*100)+'%';mallet.classList.remove('swing');void mallet.offsetWidth;mallet.classList.add('swing')}
function start(){score=0;timeLeft=cfg.duration;state='running';$('#score').textContent=score;$('#time').textContent=timeLeft;$('#startModal').classList.add('hidden');$('#finishModal').classList.add('hidden');clearInterval(timer);clearInterval(spawner);[...active.keys()].forEach(hide);spawner=setInterval(spawn,cfg.spawnEveryMs);timer=setInterval(()=>{if(state!=='running')return;timeLeft--;$('#time').textContent=timeLeft;if(timeLeft<=0)finish()},1000);spawn()}
function pause(){if(state!=='running')return;state='paused';$('#pauseModal').classList.remove('hidden')}
function resume(){if(state!=='paused')return;state='running';$('#pauseModal').classList.add('hidden')}
function finish(){state='finished';clearInterval(timer);clearInterval(spawner);[...active.keys()].forEach(hide);const won=score>=cfg.targetScore;$('#finishEyebrow').textContent=won?'CHALLENGE COMPLETE':'TIME UP';$('#finishTitle').textContent=won?'挑戰成功！':'時間到！';$('#finalScore').textContent=score+' 分';$('#finishText').textContent=won?'平安分數已準備帶回主遊戲。':`今次得到 ${score} 分，仍然可以帶回故事。`;$('#finishModal').classList.remove('hidden');tone(won?880:220,.35)}
$('#start').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#retry').onclick=start;$('#returnStory').onclick=()=>{window.parent.postMessage({complete:true,score},'*');$('#returnStory').disabled=true;$('#returnStory').textContent='正在返回故事…'};load();
