const CONFIG_ENDPOINT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/peaceBunWhack';
const $=s=>document.querySelector(s),holes=$('#holes');let config,cfg,state='loading',score=0,timeLeft=0,timer,spawner,active=new Map(),audio,hostScore=0,levelIndex=0,bunShown=0,bunHits=0,tartHits=0;
function incomingHostScore(){const raw=new URLSearchParams(location.search).get('score');if(raw!==null&&raw!==''&&Number.isFinite(+raw))return +raw;if(Number.isFinite(window.__islandScore))return +window.__islandScore;return 0}
function reportToParent(done){if(window.parent===window)return;window.parent.postMessage({type:'island-stats',set:{score:hostScore+score},complete:!!done},'*')}
window.addEventListener('message',e=>{const d=e.data;if(!d||typeof d!=='object')return;if(d.type==='island-stats'&&Number.isFinite(+d.score)&&(state==='ready'||state==='finished')){window.__islandScore=+d.score;hostScore=+d.score}});
for(let i=0;i<15;i++){const hole=document.createElement('button');hole.type='button';hole.className='hole';hole.setAttribute('aria-label',`洞口 ${i+1}`);hole.innerHTML='<span class="object"><img alt=""></span>';hole.onclick=e=>whack(i,e);holes.appendChild(hole)}const holeEls=[...document.querySelectorAll('.hole')];
async function bundledConfig(){const r=await fetch('config.json',{cache:'no-store'});if(!r.ok)throw new Error();return r.json()}async function publishedConfig(){const r=await fetch(CONFIG_ENDPOINT,{cache:'no-store'});if(!r.ok)return null;const d=await r.json(),p=d.fields?.payload?.stringValue;return p?JSON.parse(p):null}
function normalize(raw,fallback){return{version:3,texts:{...fallback.texts,...(raw?.texts||{})},settings:{...fallback.settings,...(raw?.settings||{})},levels:Array.isArray(raw?.levels)&&raw.levels.length?raw.levels:fallback.levels}}
function format(template,values){return String(template||'').replace(/\{(\w+)\}/g,(_,key)=>values[key]??'')}
function level(){return config.levels[levelIndex]}
function accuracy(){return bunShown?Math.round(bunHits/bunShown*100):0}
function updateHud(){$('#level').textContent=`${levelIndex+1} / ${config.levels.length}`;$('#time').textContent=timeLeft;$('#score').textContent=score;$('#accuracy').textContent=accuracy()+'%';$('#accuracyFill').style.width=Math.min(100,accuracy())+'%';$('#bunCounter').textContent=`${bunHits} / ${bunShown}`}
function applyConfig(){const t=config.texts;document.title=t.pageTitle;['brandLine','brandMain','brandSub','levelLabel','timeLabel','scoreLabel','accuracyLabel','helpTitle','helpText','bunLegend','tartLegend','loadingTitle','startEyebrow','startTitle','startText','pauseEyebrow','pauseTitle'].forEach(k=>{const el=$('#'+k);if(el)el.textContent=t[k]||''});$('#pause').setAttribute('aria-label',t.pauseButtonLabel);$('#start').textContent=t.startButton;$('#resume').textContent=t.resumeButton;$('#retry').textContent=t.retryButton;$('#retryLevel').textContent=t.retryLevelButton;$('#nextLevel').textContent=t.nextLevelButton;$('#returnStory').textContent=t.returnButton;$('#tartPenalty').textContent='−'+Math.abs(Number(cfg.tartPenalty)||0)+' '+t.scoreUnit;renderLevelPreview()}
function renderLevelPreview(){const box=$('#levelPreview');box.innerHTML='';config.levels.forEach((l,i)=>{const item=document.createElement('div');item.innerHTML=`<b>${format(config.texts.levelName,{level:i+1})}</b><span>${Math.round(l.duration/60)} ${config.texts.minuteUnit} · ${l.requiredAccuracy}% · +${l.reward} ${config.texts.scoreUnit}</span>`;box.append(item)})}
async function preload(){const assets=['assets/festival-board.png','assets/peace-bun-plain.png','assets/peace-bun-stamped.png'];let done=0;const update=()=>{const p=Math.round(done/assets.length*100);$('#loadFill').style.width=p+'%';$('#loadPercent').textContent=p+'%'};await Promise.all(assets.map(src=>new Promise(resolve=>{const img=new Image();const finish=()=>{done++;update();resolve()};img.onload=finish;img.onerror=finish;img.src=src})));await new Promise(r=>setTimeout(r,350));$('#preloadModal').classList.add('hidden');$('#startModal').classList.remove('hidden');state='ready'}
function tone(freq,duration=.08){try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration)}catch{}}
function spawn(){if(state!=='running')return;const free=holeEls.map((_,i)=>i).filter(i=>!active.has(i));if(!free.length)return;const l=level(),count=Math.random()<(Number(l.doubleChance)||0)?2:1,tartChance=Math.max(0,Math.min(100,Number(cfg.tartChance)||0))/100;for(let n=0;n<count&&free.length;n++){const pick=Math.floor(Math.random()*free.length),index=free.splice(pick,1)[0],isTart=Math.random()<tartChance,img=holeEls[index].querySelector('img');img.src=isTart?'':'assets/peace-bun-plain.png';img.alt=isTart?'蛋撻':'未蓋印平安包';if(!isTart)bunShown++;active.set(index,{isTart,hit:false});holeEls[index].className='hole up'+(isTart?' tart':'');const timeout=setTimeout(()=>hide(index),Number(l.visibleForMs)||1000);active.get(index).timeout=timeout}updateHud()}
function hide(index){const item=active.get(index);if(!item)return;clearTimeout(item.timeout);holeEls[index].className='hole';holeEls[index].querySelector('.feedback')?.remove();active.delete(index)}
function whack(index,event){if(state!=='running')return;const item=active.get(index);showMallet(event);if(!item||item.hit){tone(120);return}item.hit=true;clearTimeout(item.timeout);holeEls[index].classList.add('hit');let feedback;if(item.isTart){tartHits++;score-=Math.abs(Number(cfg.tartPenalty)||0);feedback='−'+Math.abs(Number(cfg.tartPenalty)||0)}else{bunHits++;feedback='+1';const img=holeEls[index].querySelector('img');img.src='assets/peace-bun-stamped.png';img.alt='已蓋印平安包'}updateHud();reportToParent(false);showFeedback(index,feedback,item.isTart);tone(item.isTart?150:580,.13);setTimeout(()=>hide(index),1000)}
function showFeedback(index,value,penalty){const badge=document.createElement('span');badge.className='feedback'+(penalty?' penalty':'');badge.textContent=value;holeEls[index].appendChild(badge)}
function showMallet(event){const box=$('#game').getBoundingClientRect(),mallet=$('#mallet');mallet.style.left=((event.clientX-box.left)/box.width*100)+'%';mallet.style.top=((event.clientY-box.top)/box.height*100)+'%';mallet.classList.remove('swing');void mallet.offsetWidth;mallet.classList.add('swing')}
function clearRound(){clearInterval(timer);clearInterval(spawner);[...active.keys()].forEach(hide)}
function startGame(){score=0;levelIndex=0;$('#startModal').classList.add('hidden');$('#finishModal').classList.add('hidden');startLevel()}
function startLevel(){clearRound();bunShown=0;bunHits=0;tartHits=0;timeLeft=Number(level().duration)||120;state='running';$('#levelModal').classList.add('hidden');updateHud();spawner=setInterval(spawn,Number(level().spawnEveryMs)||650);timer=setInterval(()=>{if(state!=='running')return;timeLeft--;updateHud();if(timeLeft<=0)finishLevel()},1000);spawn()}
function pause(){if(state!=='running')return;state='paused';$('#pauseModal').classList.remove('hidden')}
function resume(){if(state!=='paused')return;state='running';$('#pauseModal').classList.add('hidden')}
function finishLevel(){clearRound();state='level-end';const l=level(),rate=accuracy(),won=rate>=Number(l.requiredAccuracy);$('#levelEyebrow').textContent=won?config.texts.levelCompleteEyebrow:config.texts.levelFailedEyebrow;$('#levelTitle').textContent=won?format(config.texts.levelSuccessTitle,{level:levelIndex+1}):format(config.texts.levelFailedTitle,{level:levelIndex+1});$('#levelResult').textContent=format(config.texts.accuracyResult,{hits:bunHits,total:bunShown,accuracy:rate,target:l.requiredAccuracy});if(won){score+=Number(l.reward)||0;$('#levelText').textContent=format(config.texts.levelRewardText,{reward:l.reward,score});$('#retryLevel').classList.add('hidden');$('#nextLevel').classList.remove('hidden');$('#nextLevel').textContent=levelIndex===config.levels.length-1?config.texts.viewResultButton:config.texts.nextLevelButton;tone(880,.35)}else{$('#levelText').textContent=format(config.texts.levelRetryText,{target:l.requiredAccuracy});$('#retryLevel').classList.remove('hidden');$('#nextLevel').classList.add('hidden');tone(220,.35)}$('#score').textContent=score;$('#levelModal').classList.remove('hidden');reportToParent(false)}
function advance(){if(levelIndex>=config.levels.length-1)return finishGame();levelIndex++;startLevel()}
function finishGame(){state='finished';$('#levelModal').classList.add('hidden');$('#finishEyebrow').textContent=config.texts.completeEyebrow;$('#finishTitle').textContent=config.texts.successTitle;$('#finalScore').textContent=score+' '+config.texts.scoreUnit;$('#finishText').textContent=format(config.texts.successText,{score});$('#finishModal').classList.remove('hidden');reportToParent(false)}
$('#start').onclick=startGame;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#retryLevel').onclick=startLevel;$('#nextLevel').onclick=advance;$('#retry').onclick=()=>{$('#finishModal').classList.add('hidden');$('#startModal').classList.remove('hidden');state='ready'};$('#returnStory').onclick=()=>{reportToParent(true);$('#returnStory').disabled=true;$('#returnStory').textContent=config.texts.returningButton};
(async()=>{const fallback=await bundledConfig();let remote=null;try{remote=await publishedConfig()}catch(e){console.warn('Using bundled bun config',e)}config=normalize(remote?.version>=3?remote:fallback,fallback);cfg=config.settings;hostScore=incomingHostScore();applyConfig();await preload()})();
