const CONFIG_ENDPOINT='https://firestore.googleapis.com/v1/projects/island-journey-rgb/databases/(default)/documents/miniGames/peaceBunWhack';
const $=s=>document.querySelector(s),holes=$('#holes');let config,cfg,state='idle',score=0,timeLeft=30,timer,spawner,active=new Map(),audio;
const difficultyProfiles={easy:{spawnEveryMs:720,visibleForMs:1250,doubleChance:.12},normal:{spawnEveryMs:520,visibleForMs:920,doubleChance:.28},hard:{spawnEveryMs:360,visibleForMs:680,doubleChance:.45}};
for(let i=0;i<15;i++){const hole=document.createElement('button');hole.type='button';hole.className='hole';hole.setAttribute('aria-label',`洞口 ${i+1}`);hole.innerHTML='<span class="object"><img alt=""></span>';hole.onclick=e=>whack(i,e);holes.appendChild(hole)}
const holeEls=[...document.querySelectorAll('.hole')];
async function bundledConfig(){const r=await fetch('config.json',{cache:'no-store'});if(!r.ok)throw new Error();return r.json()}
async function publishedConfig(){const r=await fetch(CONFIG_ENDPOINT,{cache:'no-store'});if(!r.ok)return null;const data=await r.json(),payload=data.fields?.payload?.stringValue;return payload?JSON.parse(payload):null}
function normalize(raw,fallback){return{texts:{...fallback.texts,...(raw?.texts||{})},settings:{...fallback.settings,...(raw?.settings||{})}}}
function format(template,values){return String(template||'').replace(/\{(\w+)\}/g,(_,key)=>values[key]??'')}
async function load(){const fallback=await bundledConfig();let remote=null;try{remote=await publishedConfig()}catch(error){console.warn('Using bundled bun config',error)}config=normalize(remote||fallback,fallback);cfg=config.settings;applyConfig()}
function applyConfig(){const t=config.texts;document.title=t.pageTitle;$('#brandLine').textContent=t.brandLine;$('#brandMain').textContent=t.brandMain;$('#brandSub').textContent=t.brandSub;$('#timeLabel').textContent=t.timeLabel;$('#scoreLabel').textContent=t.scoreLabel;$('#targetLabel').textContent=t.targetLabel;$('#pause').setAttribute('aria-label',t.pauseButtonLabel);$('#helpTitle').textContent=t.helpTitle;$('#helpText').textContent=t.helpText;$('#bunLegend').textContent=t.bunLegend;$('#tartLegend').textContent=t.tartLegend;$('#startEyebrow').textContent=t.startEyebrow;$('#startTitle').textContent=t.startTitle;$('#startText').textContent=t.startText;$('#start').textContent=t.startButton;$('#pauseEyebrow').textContent=t.pauseEyebrow;$('#pauseTitle').textContent=t.pauseTitle;$('#resume').textContent=t.resumeButton;$('#retry').textContent=t.retryButton;$('#returnStory').textContent=t.returnButton;timeLeft=Number(cfg.duration)||30;$('#time').textContent=timeLeft;$('#target').textContent=Number(cfg.targetScore)||0;$('#bunPoints').textContent='+'+(Number(cfg.bunPoints)||0);$('#tartPenalty').textContent='−'+Math.abs(Number(cfg.tartPenalty)||0)}
function tone(freq,duration=.08){try{audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration)}catch{}}
function profile(){return difficultyProfiles[cfg.difficulty]||difficultyProfiles.normal}
function spawn(){if(state!=='running')return;const free=holeEls.map((_,i)=>i).filter(i=>!active.has(i));if(!free.length)return;const p=profile(),count=Math.random()<p.doubleChance?2:1,tartChance=Math.max(0,Math.min(100,Number(cfg.tartChance)||0))/100;for(let n=0;n<count&&free.length;n++){const pick=Math.floor(Math.random()*free.length),index=free.splice(pick,1)[0],isTart=Math.random()<tartChance,img=holeEls[index].querySelector('img');img.src=isTart?'':'assets/peace-bun-plain.png';img.alt=isTart?'':'未蓋印平安包';active.set(index,{isTart,hit:false});holeEls[index].className='hole up'+(isTart?' tart':'');const timeout=setTimeout(()=>hide(index),p.visibleForMs);active.get(index).timeout=timeout}}
function hide(index){const item=active.get(index);if(!item)return;clearTimeout(item.timeout);holeEls[index].className='hole';holeEls[index].querySelector('.feedback')?.remove();active.delete(index)}
function whack(index,event){if(state!=='running')return;const item=active.get(index);showMallet(event);if(!item||item.hit){tone(120);return}item.hit=true;clearTimeout(item.timeout);holeEls[index].classList.add('hit');const points=item.isTart?-Math.abs(Number(cfg.tartPenalty)||0):(Number(cfg.bunPoints)||0);score+=points;$('#score').textContent=score;showFeedback(index,points);if(!item.isTart){const img=holeEls[index].querySelector('img');img.src='assets/peace-bun-stamped.png';img.alt='已蓋印平安包'}tone(item.isTart?150:580,.13);setTimeout(()=>hide(index),1000)}
function showFeedback(index,points){const badge=document.createElement('span');badge.className='feedback'+(points<0?' penalty':'');badge.textContent=(points>0?'+':'')+points;holeEls[index].appendChild(badge)}
function showMallet(event){const box=$('#game').getBoundingClientRect(),mallet=$('#mallet');mallet.style.left=((event.clientX-box.left)/box.width*100)+'%';mallet.style.top=((event.clientY-box.top)/box.height*100)+'%';mallet.classList.remove('swing');void mallet.offsetWidth;mallet.classList.add('swing')}
function start(){score=0;timeLeft=Number(cfg.duration)||30;state='running';$('#score').textContent=score;$('#time').textContent=timeLeft;$('#startModal').classList.add('hidden');$('#finishModal').classList.add('hidden');$('#returnStory').disabled=false;clearInterval(timer);clearInterval(spawner);[...active.keys()].forEach(hide);const p=profile();spawner=setInterval(spawn,p.spawnEveryMs);timer=setInterval(()=>{if(state!=='running')return;timeLeft--;$('#time').textContent=timeLeft;if(timeLeft<=0)finish()},1000);spawn()}
function pause(){if(state!=='running')return;state='paused';$('#pauseModal').classList.remove('hidden')}
function resume(){if(state!=='paused')return;state='running';$('#pauseModal').classList.add('hidden')}
function finish(){state='finished';clearInterval(timer);clearInterval(spawner);[...active.keys()].forEach(hide);const t=config.texts,won=score>=Number(cfg.targetScore);$('#finishEyebrow').textContent=won?t.completeEyebrow:t.timeUpEyebrow;$('#finishTitle').textContent=won?t.successTitle:t.timeUpTitle;$('#finalScore').textContent=score+' '+t.scoreUnit;$('#finishText').textContent=won?t.successText:format(t.timeUpText,{score});$('#finishModal').classList.remove('hidden');tone(won?880:220,.35)}
$('#start').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#retry').onclick=start;$('#returnStory').onclick=()=>{window.parent.postMessage({complete:true,score},'*');$('#returnStory').disabled=true;$('#returnStory').textContent=config.texts.returningButton};load();
